#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "arm-openwrt-linux-uclibcgnueabi-gcc -DOPENSSL_THREADS  -DOPENSSL_NO_HEARTBEATS "
  #define PLATFORM "os/compiler"
  #define DATE "Tue Nov 18 23:55:03 PST 2014"
#endif
